### ISSUE TITLE
newbie notes - error: 'clang-c/Platform.h' file not found

### ISSUE THREAD

**Issue by johndpope** [harlanhaskins/WrapGen#1]
thus far I've tried

 brew install --with-clang llvm --force

 swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib
 swift build -Xcc "`llvm-config --cflags`" -Xlinker "-I`llvm-config --libdir`"

Compile Swift Module 'Clang' (17 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/cclang-4077381236193923946/shim.h:1:10: error: 'clang-c/Platform.h' file not found
#include <clang-c/Platform.h>
         ^
/Users/johndpope/Documents/gitWorkspace/WrapGen/.build/checkouts/ClangSwift--7853578657428638804/Sources/Clang/Availability.swift:2:8: error: could not build Objective-C module 'cclang'
import cclang
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/johndpope/Documents/gitWorkspace/WrapGen/.build/debug.yaml

**Comment by harlanhaskins** [comment]
Thanks for the report!

You've got to run `swift utils/make-pkgconfig.swift` from the `ClangSwift` repo first. Then it should build with just `swift build`

**Comment by johndpope** [comment]
it does. thanks
